//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sistema_Cliente
    {
        public int ID_Sistema { get; set; }
        public int ID_Cliente { get; set; }
        public string Version_Cliente { get; set; }
        public System.DateTime Fecha_Contrato { get; set; }
        public string Vigencia { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Sistema Sistema { get; set; }
    }
}
